Hello there!
This is a test message.
I made this to test out how ink works with unity...
Wasn't that hard hehe!
Although you can already tell that...
...
well...
There's nothing left to say...
See ya!